name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
        working-directory: frontend
      - name: build project
        run: npm run build
        working-directory: frontend
      - name: unit test
        run: npm run test:unit
        working-directory: frontend
      - name: e2e test
        run: npm run test:e2e
        working-directory: frontend
      - name: lint code
        run: npm run lint
        working-directory: frontend
      - name: type check 
        run: npm run type:check
        working-directory: frontend
      - name: i18n check
        run: npm run i18n:check
        working-directory: frontend